stages:
  - test
  - build
  - deploy

image: node:16

variables:
  # testing project name
  PROJECT_NAME_TESTING: "sample-testing-application"
  # production
  PROJECT_NAME: "sample-application"

include:
  # templates
  - local: '.gitlab-ci/template/test.yml'
  - local: '.gitlab-ci/template/build.yml'
  - local: '.gitlab-ci/template/deploy.yml'
