version: '3'
services:
  main:
    container_name: main
    build:
      context: ./main
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on: 
      - reactapp
      - vueapp
    networks:
      - frontend-compose-network
  reactapp:
    container_name: reactapp
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "81:80"
    # depends_on:
    #   - main
    networks:
      - frontend-compose-network
    volumes:
      - reactapp:/react-app
      - node_modules:/react-app/node_modules
  vueapp:
    container_name: vueapp
    build:
      context: ./vue-app
      dockerfile: Dockerfile
    ports:
      - "82:80"
    # depends_on:
    #   - main
    networks:
      - frontend-compose-network
    volumes:
      - vueapp:/vue-app
      - node_modules:/vue-app/node_modules
networks: 
  frontend-compose-network:
    driver: bridge
volumes:
  node_modules:
  vueapp:
  reactapp: